### PR TITLE
Resolve remix conflict, update to React 18 and heroicons2

### PR DESCRIPTION
**Pull request by colinasquith**
The latest version of the storefront-remix-starter project has a conflict between Remix versions in the dependencies and devDependencies when running npm install so it doesn't work straight away. This PR resolves that issue and upgrades the main libraries to the latest versions.

- Updates Remix versions to be consistent
- Update Heroicons to v2 (and fixes icon names that have moved in v2)
- Update React to v18.2
- Updates pages to be consistent with the .prettierrc settings (as the settings file is newer than some of the pages)
- Resolves a hydration issue that the <Footer> component came after the LiveReload in root.tsx which caused a hydration issue in React 18.
- Updates npm packages to resolve vulnerabilities
- Resolves some TS warnings with the non-null assertion operator
- Removes unused React import from files that don't need it

I saw Vendure at RemixConf and thought I would take a look as I need to build an ecommerce site, hope the feedback helps. I will look at the Remix user account page and may submit a PR if I make something useful for that.

### CODE REVIEW

**Comment by michaelbromley** [comment]
Colin, thanks so much for this PR! Everything looks great - I just have 1 ask - there  are a bunch of changes in here which are purely indentation-related, your IDE seems to be set to use 4 spaces rather than 2. Would you be able to set it to use 2 spaces and then reformat the affected files? That way the git history will accurately show only the lines that actually changed in a meaningful way.

Again, thanks for putting the time in on this, it is very much appreciated!

**Comment by colinasquith** [comment]
No problem @michaelbromley, I mentioned this in the PR that some files were not edited after the change to .prettierrc - the setting in .prettierrc is "tabWidth": 4, so as I edited the files they have been updated to 4 spaces. I can update the .prettierrc to 2 and re-edit if 2 is the preference?

**Comment by michaelbromley** [comment]
Ah ok that's weird then that all the existing files are using 2 spaces. OK so let's set to 2 spaces then. Personally I have no strong preference either way, but I'd prefer the git history to show just the meaningful changes for this PR.

**Comment by colinasquith** [comment]
I've edited the prettier settings and regenerated, although any files that were updated before the .prettierrc changed in May were on 2 spaces, and any files edited after were on 4 from the settings so the files were mixed settings. I think it's best for me to take out any files that don't have other changes than spacing from my PR, and the spacing will be consistent when someone next edits those files. E.g. AddressForm.tsx is an example where the spacing looks to be 4 already in the repo. Let me know what you think and I can update.

**Comment by michaelbromley** [comment]
yep, it turns out the spacing was just generally a mess all along 😆 
Agree, just include the files that actually have your changes, and then if you like you can do a second PR to update the formatting of all the remaining files to get things in a consistent state.

**Comment by colinasquith** [comment]
Ok @michaelbromley - I've switched off Prettier and remade the changes, so it doesn't affect formatting for the React 18/Heroicons/Remix changes. I'm happy to run everything through Prettier as separate PR - just be aware that the settings would switch some single quotes to double quotes and add semicolons to the ends of lines to make them all consistent as there's a mixture of spacing, quotes and semicolons in the current files.

**Comment by michaelbromley** [comment]
Thanks so much for this PR! This is the kind of maintenance work it is _really_ hard for me to keep on top of when I am looking after so many repos, especially since I'm not primarily a React or Remix dev, so sometimes this kinda stuff takes me longer than it should.

I think it makes sense to get everything into a consistent state now, so this topic doesn't come up again. I guess we should have some kind of automation on this - in the main Vendure repo I use husky + lint-staged to make it so no commits ever land with formatting issues. 

So yeah I'd love a PR that gets everything consistent. If you wanna take it further with something like lint-staged, that would be amazing but only if you have the time & willingness - no expectation from me that you should :)

**Comment by colinasquith** [comment]
I was impressed with all the integrations and projects! A lot to keep up on, and makes sense since I need to build and tidy a few things to try out the Remix storefront to make those changes and push them back! I haven't used Husky or lint-staged but always great to learn about new tools! PR incoming!

**Pull request merged**
