### PR TITLE
Product image gallery

### PR DESCRIPTION
**Pull request by kyunal**
Implements https://github.com/vendure-ecommerce/storefront-remix-starter/issues/11

Product image changes based on the selected variant and a preview is provided for all product images which is scrollable and draggable both on mobile and touch. CSS/JS/React only.

Note: The demo API only has one picture per product and none per variant which means you won't see a difference unless you use your own data or modify the seed data. Be sure that the featured asset for specific variants also exists as a product picture. Changing the image preview will still work if it doesn't exist, but it won't appear in the gallery.

### CODE REVIEW

**Comment by kyunal** [comment]
We've identified an issue with scroll speeds, I'll be looking into that first before the changes should be merged.

**Comment by michaelbromley** [comment]
Hey, thanks for this contribution! 
Is the scroll speed issue sorted now?

**Comment by kyunal** [comment]
It's functional but not ideal. We have found the current setup to work fine in most cases, and it allows for horizontal scrolling on touchpads, but it's not entirely smooth since it literally just applies the delta values to the scroll of the underlying container. This is entirely dependant on the delta values provided by the `WheelEvent` class, which doesn't seem to be all that consistent across browsers. [See here](https://github.com/0xCB-dev/storefront-remix-starter/blame/63f3aa55c9669ccc86c0bb1e8549951df81ac9a7/app/components/products/ScrollableContainer.tsx#L51-L56) for further reference of how I have currently implemented it.

If you have a better solution at hand, feel free to tell :sweat_smile:. Maybe there's a trick or two that I'm not aware of. In case you want to test it, scrolling only works for >4 images and dragging is about seamless.

**Comment by michaelbromley** [comment]
Tested it out locally and I think it's fine for now. Yeah, it could be a bit smoother with the wheel, but it's perfectly functional as it is. Thanks again!

**Pull request merged**
