### PR TITLE
feat: rework account page, add address management

### PR DESCRIPTION
**Pull request by mitch3s**
Rework account page:

* Add remix-validated-form package for form validation
* Rework input components
* Rework modal
* Split email from profile form
* Add address management
* Add password change

I'm quite new to this stack so any feedback for improvements is welcome! Only thing missing from the account page for now is the order history.

image
image
image
image
image

### CODE REVIEW

**Comment by kyunal** [comment]
Thank you for this **_huge_** contribution! I noticed a lot more work than what you have mentioned, e.g. reworking & abstracting the account navbar. This is a big leap forward for the remix storefront and includes some long awaited features & ground-work (e.g. input validation).

I think the modals in particular are great. The modal used to create/edit a new address could be reused in checkout to allow users to create new addresses on the fly.

In terms of address management, setting a default shipping/billing address is still missing. But this is a shortcoming of the remix storefront overall, as these are also missing in the checkout (differentiating between shipping and billing address is missing entirely.).

Another nitpick from me is the fact that the password tab in account management only shows a single button right now. I don't think this is ideal, we could either always display the change password form or use a modal whenever the password tab is selected but stay on the same tab.

In my opinion none of the things I've mentioned are worth addressing immediately, so I'll go ahead and merge these changes. I'll do some updates in the docs in the near future so we can keep track of these things more easily.

cc @michaelbromley, definitely worth mentioning in your Friday reviews :wink:

**Comment by mitch3s** [comment]
> Thank you for this **_huge_** contribution! I noticed a lot more work than what you have mentioned, e.g. reworking & abstracting the account navbar. This is a big leap forward for the remix storefront and includes some long awaited features & ground-work (e.g. input validation).
> 
> I think the modals in particular are great. The modal used to create/edit a new address could be reused in checkout to allow users to create new addresses on the fly.
> 
> In terms of address management, setting a default shipping/billing address is still missing. But this is a shortcoming of the remix storefront overall, as these are also missing in the checkout (differentiating between shipping and billing address is missing entirely.).
> 
> Another nitpick from me is the fact that the password tab in account management only shows a single button right now. I don't think this is ideal, we could either always display the change password form or use a modal whenever the password tab is selected but stay on the same tab.
> 
> In my opinion none of the things I've mentioned are worth addressing immediately, so I'll go ahead and merge these changes. I'll do some updates in the docs in the near future so we can keep track of these things more easily.
> 
> cc @michaelbromley, definitely worth mentioning in your Friday reviews 😉

Great, thanks for the feedback! 🙂

It would also be good to unify the address form on the checkout page (when not logged in) with the new address form, since most fields and validation are the same. I might still work on that later, for now I was just focusing on the account page.

And regarding the password tab: you're right, it indeed looks a bit strange this way. A modal might fit there, perhaps the button could then be even moved to the first tab entirely.

**Comment by zolzaya** [comment]
Nice thanks :)

**Comment by michaelbromley** [comment]
@mitch3s thank you for these excellent improvements! This is definitely getting a shout-out in my next review post 👍

**Pull request merged**
